name: Software update
on:
  workflow_dispatch
  branches: main
jobs:
  new-release:
    steps:
      - uses: actions/checkout@v3 
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3
      
       - name: Create release
         uses: actions/create-release@v1 
